/* Fictional, offline file-sharing and document-preview interface. */
function archiveShell(title,body,{folder='mirror',aside='',mode='files',subtitle=''}={}){
 const folders=[['mirror','广播站旧资料'],...(state.board?[['board','工作台导出文件']]:[]),...(state.vault?[['vault','历史档案扫描件'],['case','核对往来']]:[])];
 const folderName=folder==='mirror'?'广播站旧资料':folder==='vault'||folder==='case'?'历史档案扫描件':'工作台导出文件';
 return `<section class="archive-web ${mode==='preview'?'archive-preview':''}"><header class="archive-web-header"><a class="archive-wordmark" href="#mirror"><svg class="qiyun-mark" viewBox="0 0 32 26" aria-hidden="true"><path d="M9 21h15a6 6 0 0 0 1-12 9 9 0 0 0-17-2 7 7 0 0 0 1 14Z" fill="currentColor"/><path d="m11 14 4-4 4 4m-4-4v10" fill="none" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>栖云盘</a><span>文件分享</span><span class="cloud-visitor">访客 · 只读访问</span><a href="#home">返回学校网站</a></header><div class="archive-web-layout"><nav class="archive-nav" aria-label="云盘分享目录"><small>分享给我的</small>${folders.map(([id,label])=>`<a href="#${id}" ${folder===id?'aria-current="page"':''}><span class="cloud-folder-icon" aria-hidden="true"></span>${label}</a>`).join('')}<a href="#search?scope=private">搜索分享文件</a><small>联系分享者</small><a href="#chat/zhou">周栩 · 微信</a>${state.chat.answers['zhou-source']?'<a href="#chat/clerk">折页 · 微信</a>':''}<p class="cloud-side-note">分享者保留了文件原始日期。扫描件、邮件与网页均可在线预览。</p></nav><div class="archive-workspace"><div class="archive-path"><a href="#mirror">收到的分享</a><span> / </span><a href="#${folder==='case'?'vault':folder}">${folderName}</a><span> / </span><span>${esc(title)}</span></div><header class="archive-file-heading"><div><h1>${esc(title)}</h1>${subtitle?`<p>${subtitle}</p>`:''}</div><span class="archive-readonly">${mode==='preview'?'在线预览':'文件夹分享'}</span></header><div class="archive-content ${aside?'with-inspector':''}"><div class="archive-primary">${body}</div>${aside?`<aside class="archive-inspector">${aside}</aside>`:''}</div></div></div><footer class="cloud-footer"><span>栖云盘 · 文件分享</span><span>文件由分享者提供</span></footer></section>`;
}
function archiveKind(d){return d.id==='radio-index'?'WAV':d.category==='forum'?'网页':/邮件|回信/.test(d.title)?'邮件':/照片|留影|图册|夹页|残片/.test(d.title)?'扫描':'文档';}
function archiveFileRows(ids){return `<div class="archive-file-table"><div class="archive-columns" aria-hidden="true"><span>文件名称</span><span>文件日期</span><span>操作</span></div><ul class="archive-files">${ids.map(doc).filter(Boolean).map(d=>`<li><a class="archive-file-row" href="#doc/${d.id}" aria-label="打开 ${esc(d.title)}"><span><i class="file-symbol" aria-hidden="true">${archiveKind(d)}</i><span><strong>${esc(d.title)}</strong><small>${esc(d.source)}<span class="file-date-inline"> · ${d.date}</span></small></span>${state.visited.includes(d.id)?'<em>已打开</em>':''}</span><time>${d.date}</time><span class="archive-file-open" aria-hidden="true">打开 ›</span></a></li>`).join('')}</ul></div>`;}

function archiveInfo(d){return `<h2>文件信息</h2><dl><dt>来源</dt><dd>${esc(d.source)}</dd><dt>${esc(d.dateLabel||'形成日期')}</dt><dd>${d.date}</dd><dt>访问权限</dt><dd>只读副本</dd></dl><h2>关联文件</h2><ul>${(related[d.id]||[]).filter(id=>allowed(doc(id))).map(id=>`<li><a href="#doc/${id}">${esc(doc(id).title)}</a></li>`).join('')||'<li>同目录暂无关联项</li>'}</ul><a href="#search?scope=private">搜索留存文件</a>`;}
function archiveDocument(d){
 const mail=/邮件|回信/.test(d.title),forum=d.category==='forum';
 const meta=mail?`<div class="archived-mail-meta"><p><span>主题</span>${esc(d.title)}</p><p><span>来源</span>${esc(d.source)}</p><p><span>${esc(d.dateLabel||'日期')}</span>${d.date}</p></div>`:`<div class="document-metadata">${esc(d.source)}<span>${d.dateLabel?esc(d.dateLabel)+' · ':''}${d.date}</span></div>`;
 const next=d.id==='carbon'?'<a href="#chat/zhou">在微信中与周栩核对 →</a>':d.id==='cabinet-note'?'<a href="#vault">返回加密资料 →</a>':d.id==='bait'?'<a href="#invitation">查看接引登记 →</a>':state.vault?'<a href="#case">返回核对往来 →</a>':'';
 return archiveShell(d.title,`<div class="document-toolbar"><span>${mail?'邮件留存':forum?'网页留存':'原始内容'} · 只读</span><button data-action="back">返回上一页</button></div><article class="document-paper article ${mail?'archived-mail':''} ${forum?'archived-forum':''}">${mail?'':`<h1>${esc(d.title)}</h1>`}${meta}${d.body}${scrapAttachment(d.id)}<footer class="document-footer">${next}<p>文件来源与形成日期保留，不补写缺失内容。</p></footer></article>`,{folder:d.gate==='mirror'?'mirror':d.gate==='vault'?'vault':'board',mode:'preview',aside:archiveInfo(d)});
}
const previousGateView=gate;
gate=function archiveGate(k){
 if(k==='board'&&!state.mirror)return gate('mirror');if(k==='vault'&&!state.board)return gate('board');
 const titles={mirror:'广播站旧资料',board:'同灯理事会 · 工作台导出文件',vault:'历史档案扫描件'};
 if(state[k]){
  const ids=k==='mirror'?['radio-index','programme','loan','forum','letter-liang']:k==='board'?['board-index','handover','positions','cabinet-note','current-list']:ARCHIVE.filter(d=>d.gate==='vault').map(d=>d.id);
  const note=k==='mirror'?'周栩：旧硬盘里的文件都转到这里了。先听广播索引，再按两个字母查剪报袋。附件仍放在原材料旁边，日期也没改。':k==='board'?'折页：这是我导出的文件，由周栩转存。交接便笺和今年的名单放在前面。历史扫描件保留了原档案柜的访问码，需要对照灯位标签和换柜记录。':'周栩：扫描件都留在这里。我们分别核对的三件事，我放进“核对往来”了。';
  return archiveShell(titles[k],`<div class="cloud-share-owner"><span class="cloud-owner-avatar" aria-hidden="true">周</span><div><strong>周栩</strong><span>分享了此文件夹${k==='mirror'?'':' · 原始资料由折页提供'}</span></div><span class="cloud-share-permission">仅查看</span></div><div class="archive-note">${note}${k==='vault'?'<p><a href="#case">打开核对往来 →</a></p>':''}</div><div class="cloud-list-heading"><span>${k==='board'?'常用文件':'全部文件'} · ${ids.length} 项</span><a href="#search?scope=private">搜索此分享</a></div>${archiveFileRows(ids)}${k==='board'?'<details class="archive-extra"><summary>其他附件 · 7 项</summary>'+archiveFileRows(['mentor-mail','arrival','rules','bait','effigy','chant','eye-catalogue'])+'</details>':''}<div class="archive-actions">${k==='mirror'?'<a href="#doc/mirror-index">分享说明.txt</a>':''}<a href="#${k==='mirror'?'board':k==='board'?'vault':'case'}">${k==='mirror'?'查看另一份分享':k==='board'?'打开加密文件夹':'打开核对往来'} →</a></div>`,{folder:k,subtitle:'收到的分享 / 文件夹'});
 }
 const lock=previousGateView(k).replace(/^.*?<section[^>]*>/,'').replace(/<\/section>$/,'').replace(/<span class="eyebrow">.*?<\/span>/,'').replace(/<h1>.*?<\/h1>/,'');
 return archiveShell(titles[k],`<div class="archive-lock"><div class="cloud-lock-folder" aria-hidden="true"><span class="cloud-folder-icon"></span></div><p class="cloud-lock-owner">周栩分享的文件夹</p><h2>${k==='board'?'等待分享者确认':k==='mirror'?'请输入分享提取码':'此文件夹已加密'}</h2>${lock}</div>`,{folder:k==='vault'?'board':'mirror'});
};
radioPage=function archiveAudioView(){
 if(!state.mirror)return gate('mirror');markInvestigationRead('radio-index');
 const reference=`<h2>文件信息</h2><dl><dt>文件名</dt><dd>索引练习_03.wav</dd><dt>大小</dt><dd>155 KB</dd><dt>录音长度</dt><dd>00:03.6 / 单声道</dd><dt>来源</dt><dd>广播站剪报袋索引<br>周栩重新合成的短码副本</dd></dl><h2>随附资料</h2><details class="morse-reference"><summary>短码对照表.txt</summary><p>· 短音　— 长音<br>较长停顿分隔字母。</p><div>${Object.entries(MORSE).map(([k,v])=>`<span><b>${k}</b> ${v.replaceAll('-','—').replaceAll('.','·')}</span>`).join('')}</div></details><details class="signal-transcript"><summary>无法听音：文字转录</summary><p>录音的长短音记录。</p><div class="wave-bars" aria-label="信号为长短短，间隔，长"><i class="long"></i><i></i><i></i><b>/</b><i class="long"></i></div></details>`;
 const audio=`<div class="audio-file-preview" data-radio><i class="file-symbol" aria-hidden="true">WAV</i><h2>索引练习_03.wav</h2><small>音频预览 · 00:03.6</small><audio id="signal-audio" controls preload="auto" aria-label="剪报索引录音"><source src="./assets/radio-index-03.wav" type="audio/wav"></audio><p id="signal-status" role="status">准备播放…</p><div class="audio-actions"><button data-local="audio" id="play-signal">重新收听</button><button data-local="audio-stop">停止</button></div></div>`;
 const comment='<div class="file-comment"><strong>周栩</strong><time>6 月 15 日</time><p>广播社团以前用两个字母标剪报袋，知遥把字母敲成短码。我按旧记录重新合成了一遍，先听听是哪两个字母。对照表也附在这里。</p></div>';
 const lookup=state.investigation.morse?'<div class="verified-box"><h2>DT</h2><p>周栩：是这个索引。你在留存资料里搜一下。</p><a href="#search?scope=private">搜索文件 →</a></div>':'<form id="signal-form" class="file-lookup"><label for="signal-answer">剪报袋索引</label><div class="search-row"><input id="signal-answer" name="answer" maxlength="12" autocomplete="off" placeholder="录音里的两个字母"><button class="primary">核对索引</button></div><p id="signal-error" class="error" role="status"></p></form>';
 return archiveShell('索引练习_03.wav',audio+comment+lookup,{folder:'mirror',mode:'preview',aside:reference});
};
function tilePage(){
 if(!state.mirror)return gate('mirror');
 if(!state.investigation.morse)return archiveShell('DT · 传习页残片','<div class="archive-lock"><h2>请核对文件袋索引</h2><p>保存的残纸需要与广播站索引对应，才能确认来自同一份夹页。</p><a href="#doc/radio-index">打开索引录音 →</a></div>',{folder:'mirror'});
 markInvestigationRead('torn-leaf');const a=state.investigation.tiles,owned=state.investigation.collected,done=GameCore.tilesComplete(state);
 const scan=`<div class="document-toolbar"><span>扫描件拼接副本 · 已保存 ${owned.length}/4 张</span><button data-local="tile-reset">重置位置</button></div><div class="scan-workspace"><div class="tile-layout ${done?'complete':''}"><div class="tile-board" aria-label="四格残页拼图">${a.map((n,i)=>n===null?`<button class="tile empty-tile" data-slot="${i}" aria-label="第 ${i+1} 格，空白">${i+1}</button>`:tileButton(n,i)).join('')}</div><div class="tile-tray" aria-label="已保存的待拼纸片">${[2,0,3,1].filter(n=>owned.includes(n)&&!a.includes(n)).map(n=>tileButton(n)).join('')}${owned.length===0?'<p class="scrap-empty">手机里还没有保存的纸片。请先回到原始材料保存附件。</p>':''}</div></div><div class="scan-status"><p id="tile-feedback" role="status">${done?'接缝核对完成。':owned.length<4?`还缺 ${4-owned.length} 张纸片；已保存的可以先试拼。`:'可拖动纸片；也可先选纸片，再选放置位置。'}</p>${done?'<span>已保存位置</span>':'<button data-local="tile-check">核对接缝</button>'}</div></div>`;
 const result=done?'<div class="verified-box"><h2>有名者来，无名者留</h2><p>页脚：归灯前七夜</p><a href="#search?scope=private">按页上的用语搜索留存文件 →</a></div>':'';
 const trace=`<h2>周栩的备注</h2><p>知遥不肯把原件放在同一个地方。四片纸分别留在不同材料旁，先保存到手机，再试着把圆纹接起来。</p><p>装订线朝左，方向没转过。重置位置只把纸片移回桌面，不会删除手机里的副本。</p><details class="scrap-trace"><summary>查看周栩的转存记录</summary><p>节目单旁、借阅单背面、旧帖本地附件，还有梁老师后来发来的邮件，各夹着一角。</p>${SCRAPS.map(item=>`<p><a href="#doc/${item.source}">${esc(doc(item.source).title)}</a> · ${owned.includes(SCRAPS.indexOf(item))?'已保存纸片':'尚未保存纸片'}</p>`).join('')}</details>`;
 return archiveShell('DT · 传习页残片',scan+result,{folder:'mirror',mode:'preview',aside:trace});
}
