(function(root){
'use strict';
const clean=v=>String(v??'').normalize('NFKC').toLowerCase().replace(/[\s:：·，,。._\-/]/g,'');
const required=['printing','carbon','ledger','dutylog','arrival','yuan-order','recording','finance','bailu-now','witness'];
function fresh(){return {version:2,caseDraft:{},chat:{answers:{},evidence:{},seen:{}},horror:true,started:false,mirror:false,board:false,vault:false,caseSolved:false,visited:[],bookmarks:[],notes:'',endings:[],ending:null,motion:!root.matchMedia?.('(prefers-reduced-motion: reduce)').matches,startedAt:null,updatedAt:null};}
function restore(raw,ids){let s=fresh();if(!raw||raw.version!==2)return s;for(const k of ['started','mirror','board','vault','caseSolved','motion','horror'])if(typeof raw[k]==='boolean')s[k]=raw[k];s.chat=root.ChatStory?root.ChatStory.restore(raw.chat):s.chat;s.board=s.mirror&&s.board;s.vault=s.board&&s.vault;s.caseSolved=s.vault&&s.caseSolved;for(const k of ['visited','bookmarks'])s[k]=[...new Set(Array.isArray(raw[k])?raw[k].filter(x=>ids.includes(x)):[])];s.notes=typeof raw.notes==='string'?raw.notes.slice(0,30000):'';s.endings=[...new Set(Array.isArray(raw.endings)?raw.endings.filter(x=>['good','bad','neutral'].includes(x)):[])];s.ending=s.endings.includes(raw.ending)?raw.ending:null;if(raw.caseDraft&&typeof raw.caseDraft==='object')for(const k of ['name','alias','memorial','next','place','date','time','proofCount','proofChange','proofIdentity','proofCaptivity','proofJourney','proofMoney'])if(typeof raw.caseDraft[k]==='string')s.caseDraft[k]=raw.caseDraft[k].slice(0,80);s.startedAt=Number.isFinite(raw.startedAt)?raw.startedAt:null;return s;}
function canRead(s,d){return !!d&&(!d.gate||s[d.gate]===true);}
function unlock(s,gate,input){if(gate==='mirror'){if(clean(input.password)!=='1840')return '口令不匹配。请核对广播正式停播的时刻，使用四位数字。';s.mirror=true;return null;}if(gate==='board'){if(!s.mirror)return '请先打开周栩的留存包。';if(clean(input.account)!=='074'||clean(input.password)!=='有灯无人')return '工作证编号或口令不匹配。请核对节目单与谈话记录，保留编号前导零。';s.board=true;return null;}if(gate==='vault'){if(!s.board)return '请先打开理事工作台副本。';if(clean(input.password)!=='842')return '顺序不匹配。请对照三次停灯的方位，依次取对应数字。';s.vault=true;return null;}return '未知资料来源。';}
function solveCase(s,f){if(!s.vault)return '尚未打开原始档案柜。';if(required.some(x=>!s.visited.includes(x)))return '还有关键原始材料未阅读，请先核对下方的材料清单。';const fields=[['name','许知遥','2018 年失踪者的原名'],['alias','听潮','原名与会内称呼的对应'],['memorial','何宁','仪式所纪念的人'],['next','陈予安','今年接送的对象'],['place','东堤北院','修订后的接收地点'],['date','20280617','接送日期'],['time','2110','修订后的到达时间']];for(const [k,v,label]of fields)if(clean(f[k])!==clean(v))return label+'尚未与记录对应，请再核对相关材料。';const pairs={proofCount:'printing',proofChange:'yuan-order',proofIdentity:'ledger',proofCaptivity:'dutylog',proofJourney:'arrival',proofMoney:'finance'};for(const [k,v]of Object.entries(pairs))if(f[k]!==v)return '有一项判断还没有选中能直接支持它的材料。请区分公开宣传、私人陈述与原始记录。';s.caseSolved=true;return null;}
function finish(s,type){if(!['good','bad','neutral'].includes(type))return '未知结局。';if(type==='good'&&(!s.caseSolved||!s.vault||required.some(x=>!s.visited.includes(x))))return '请先完成事实与证据核对。';if(type==='bad'&&(!s.board||!s.visited.includes('bait')))return '尚未收到接引邀请。';s.ending=type;if(!s.endings.includes(type))s.endings.push(type);return null;}
const api={fresh,restore,canRead,unlock,solveCase,finish,clean,required};root.GameCore=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
