/* Private archive reading flow; all content is rendered only after the relevant gate. */
function archiveFiles(ids){return `<ul class="file-list">${ids.map(doc).filter(Boolean).map(d=>`<li><a href="#doc/${d.id}">${d.title}</a><small>${state.visited.includes(d.id)?'已读 · ':''}${d.source} · ${d.date}</small></li>`).join('')}</ul>`;}
function gate(k){
  if(k==='board'&&!state.mirror)return gate('mirror');
  if(k==='vault'&&!state.board)return gate('board');
  const titles={mirror:'周栩的网页留存包',board:'同灯理事会 · 工作台副本',vault:'历史档案柜'};
  if(state[k]){
    if(k==='vault')return `<div class="workbench-brand"><strong>历史档案柜</strong><span>折页保全的原始副本</span></div><section class="panel reading-start"><span class="eyebrow">周栩 · 新消息</span><h1>一起把经过读完</h1><p>“文件都在了。你不用再把名字和时间抄一遍，我们按事情发生的顺序，慢慢看。”</p><p>接下来一起读三段经过，拼回一张纸条，再对照两份通知。原始文件附在各段后面，可以随时回看；不需要逐一打开全部档案。</p><a class="button-link primary" href="#case">${state.caseSolved?'回看整理与最后的决定':'和周栩继续阅读'} →</a><details class="archive-extra"><summary>想继续查原件与异常记录</summary><p class="help-note">以下是补充阅读，可以按兴趣查看，不影响进入最后的决定。</p>${archiveFiles(ARCHIVE.filter(d=>d.gate==='vault').map(d=>d.id))}</details></section>`;
    const ids=k==='mirror'?['mirror-index','programme','loan','forum','letter-liang']:['board-index','handover','positions','cabinet-note','current-list'];
    return `<div class="${k==='board'?'workbench-brand':'mirror-banner'}"><strong>${titles[k]}</strong><span>本地保全副本 · 与公开官网分开存放</span></div><section class="panel"><h1>${titles[k]}</h1><p>${k==='mirror'?'先读当晚的记录，再看梁老师后来发来的邮件。她留下的复写联，会让周栩想起一位能帮上忙的联系人。':'先看交接便笺和今年的名单。要打开档案柜，将灯位对照与换柜记录放在一起看。'}</p>${archiveFiles(ids)}<div class="dialog-actions"><a class="button-link" href="#search?scope=private">检索留存资料</a><a class="button-link" href="#${k==='mirror'?'board':'vault'}">${k==='mirror'?'理事工作台':'历史档案柜'} →</a></div>${k==='board'?'<details class="archive-extra"><summary>其他留存附件 · 可继续探索</summary>'+archiveFiles(['mentor-mail','arrival','rules','bait','effigy','chant','eye-catalogue'])+'</details>':''}</section>`;
  }
  if(k==='board'){
    let body;
    if(state.chat.evidence['clerk-intro']==='carbon')body='<p>折页：复写联上的压字和原件一致。我把副本入口发过来了，旧工作证和口令已经替你处理好。</p><button class="primary" data-action="open-board">打开折页发来的副本</button>';
    else if(state.chat.answers['zhou-source'])body='<p>周栩已经介绍了资料员“折页”。先在会话里发送梁老师的复写联，对方核对来源后就会发来入口。</p><a class="button-link primary" href="#chat/clerk">回到折页的会话 →</a>';
    else if(state.visited.includes('carbon'))body='<p>你已经找到梁老师的复写联。周栩看过同一张单子，正在等你回复，之后会介绍能提供工作台副本的资料员。</p><a class="button-link primary" href="#chat/zhou">查看周栩的新消息 →</a>';
    else body='<p>周栩：有人愿意提供副本，但我们得先核对材料是不是同一份。梁老师的邮件里提到一张留有压字的复写联，先从那里看起。</p><a class="button-link primary" href="#doc/letter-liang">阅读梁老师的邮件 →</a>';
    return `<section class="panel search-panel gate-panel"><span class="eyebrow">联系人提供的资料</span><h1>${titles[k]}</h1>${body}<p class="help-note">通过游戏内会话核对来源，不需要填写账号密码。</p></section>`;
  }
  return `<section class="panel search-panel gate-panel"><span class="eyebrow">LOCAL ARCHIVE / 本地资料</span><h1>${titles[k]}</h1><p>${k==='mirror'?'周栩发来的个人备份。口令是毕业晚会那晚广播停止的时刻，四位数字。':'把换柜记录的三次停灯方位与灯位标签对应，依次取三个数字。'}</p><form id="gate-form" data-gate="${k}"><label for="password">${k==='vault'?'开柜顺序（三位数字）':'文件口令（四位数字）'}</label><input id="password" name="password" autocomplete="off" inputmode="numeric" maxlength="30" required><div class="dialog-actions"><button class="primary">打开资料</button></div><p id="form-error" class="error" role="alert"></p></form>${k==='vault'?'<div class="gate-references"><a href="#doc/positions">回看灯位对照</a><a href="#doc/cabinet-note">回看三次停灯记录</a></div>':''}<p class="help-note">这是游戏内的文件锁，请勿输入真实账号密码。</p><a href="#${k==='mirror'?'home':'board'}">← 返回${k==='mirror'?'学校官网':'工作台'}</a></section>`;
}
function casePage(){
  if(!state.vault)return `<section class="panel search-panel"><h1>调查整理</h1><p>先打开历史档案柜。周栩会和你一起把事情的经过读完，不需要另外填表。</p><div class="dialog-actions"><a class="button-link" href="#${state.board?'vault':state.mirror?'board':'home'}">继续调查 →</a><button data-action="retreat">停止调查</button></div></section>`;
  const i=state.reviewStep,c=CASE_CHAPTERS[i],done=!!state.caseRead[c.id],puzzleDone=i===0||(i===1?state.readingPuzzles.note.length===3:state.readingPuzzles.route);
  return `<div class="mirror-banner">个人会话整理 / 6 月 15 日</div><section class="reading-room"><nav class="reading-progress" aria-label="阅读进度">${CASE_CHAPTERS.map((x,n)=>`<span ${n===i?'aria-current="step"':''}>${state.caseRead[x.id]?'✓':n+1} ${x.label}</span>`).join('')}</nav><article class="reading-scene"><span class="eyebrow">一起读完这件事 · ${i+1} / 3</span><h1>${c.title}</h1><p class="reading-intro">${c.intro}</p><div class="reading-prose">${c.paragraphs.slice(0,i?2:c.paragraphs.length).map(p=>`<p>${esc(p)}</p>`).join('')}${i?readingPuzzle(i):''}${i&&puzzleDone?c.paragraphs.slice(2).map(p=>`<p>${esc(p)}</p>`).join(''):''}</div>${puzzleDone?`<div class="reading-reply">${c.reply.map(p=>`<p>${esc(p)}</p>`).join('')}</div>`:''}<details class="reading-sources"><summary>回看这一段用到的原始材料</summary><p class="help-note">来源已按这一段对应好，不需要重新选择或填写。</p>${archiveFiles(c.documents)}</details><details class="reading-sources"><summary>还想了解更多 · 可选阅读</summary><ul class="related-list">${c.extras.map(([id,label])=>`<li><a href="#${id.includes('/')?id:'doc/'+id}">${label}</a></li>`).join('')}</ul></details><div class="reading-actions">${i?'<button data-action="previous-chapter">← 上一段</button>':''}${puzzleDone&&i<2?`<button class="primary" data-action="read-chapter" data-id="${c.id}">继续读：${CASE_CHAPTERS[i+1].label} →</button>`:puzzleDone&&!done?'<button class="primary" data-action="read-chapter" data-id="arrival">读完了，看看最后的决定 →</button>':''}</div>${i===2&&done?'<div class="verified-box" tabindex="-1"><h2>最后，怎么做？</h2><p>经过与来源已经整理好。接下来由你决定。</p><div class="ending-choices"><button class="primary" data-action="submit-case">和周栩一起，把材料交出去</button><button data-action="retreat">我害怕了，决定停止调查</button><a class="button-link" href="#invitation">我仍想看看独自赴约的条件</a></div></div>':''}</article><p class="reading-pause">可以随时离开休息，阅读进度会保留。</p></section>`;
}

function readingPuzzle(step){
 if(step===1){
  const pieces=['我原来的名字叫许知遥。','我不愿继续留在这里。','请把这句话原样交出去，不要只告诉别人我活着。'];
  const order=state.readingPuzzles.note,complete=order.length===3;
  return `<section class="paper-puzzle" aria-label="拼回求助纸条"><span class="eyebrow">值班簿的折角里</span><h2>这张纸，还没有读完</h2><p class="puzzle-instruction">${complete?'三段已经接上。继续往下读。':'按意思依次点三张纸片：先是名字，再是他的意愿，最后是给收信人的提醒。'}</p>${!complete?`<div class="paper-pieces">${[1,2,0].filter(n=>!order.includes(n)).map(n=>`<button data-action="note-piece" data-piece="${n}" class="paper-piece">${pieces[n]}</button>`).join('')}</div>`:''}<div class="assembled-note" aria-live="polite">${order.length?order.map(n=>`<p>${pieces[n]}</p>`).join(''):'<span>点过的纸片会接在这里。</span>'}</div><p id="puzzle-feedback" role="status"></p></section>`;
 }
 const complete=state.readingPuzzles.route;
 return `<section class="paper-puzzle" aria-label="对照接送通知"><span class="eyebrow">同一件事，两份通知</span><h2>哪一张还在执行？</h2><p class="puzzle-instruction">${complete?'修订版已保留。旧版只作为对照。':'看日期和页边的修订说明，留下真正执行的那张。'}</p><div class="notice-pair"><article class="notice-sheet ${complete?'obsolete':''}"><small>第一版 · 2028.06.10</small><h3>项目接送安排</h3><p>陈予安<br>6 月 17 日 · 20:30<br>明心研学营南院</p>${complete?'<strong class="notice-stamp">已作废</strong>':'<button data-action="choose-notice" data-notice="old">保留这张</button>'}</article><article class="notice-sheet ${complete?'retained':''}"><small>修订版 · 2028.06.14</small><h3>北院接收通知</h3><p>陈予安<br>6 月 17 日 · 21:10<br>东堤北院 · 河堤便道</p><p class="revision-note">本版替代 6 月 10 日安排。</p>${complete?'<strong class="notice-stamp">执行此版</strong>':'<button data-action="choose-notice" data-notice="revised">保留这张</button>'}</article></div><p id="puzzle-feedback" role="status"></p></section>`;
}
