/* Private archive reading flow; all content is rendered only after the relevant gate. */
function archiveFiles(ids){return archiveFileRows(ids);}
function gate(k){
  if(k==='board'&&!state.mirror)return gate('mirror');
  if(k==='vault'&&!state.board)return gate('board');
  const titles={mirror:'周栩的网页留存包',board:'同灯理事会 · 工作台副本',vault:'历史档案柜'};
  if(state[k]){
    if(k==='vault')return `<div class="workbench-brand"><strong>历史档案柜</strong><span>折页保全的原始副本</span></div><section class="panel reading-start"><span class="eyebrow">周栩 · 新消息</span><h1>一起把经过读完</h1><p>“文件都在了。你不用再把名字和时间抄一遍，我们按事情发生的顺序，慢慢看。”</p><p>有三件事要分别找人核实：谁改了外面的记录、所谓近期消息的原始日期，以及两天后的接收安排。材料按问题放在下面，先判断，再在微信里发给联系人。</p><a class="button-link primary" href="#case">${state.caseSolved?'回看整理与最后的决定':'和周栩继续阅读'} →</a><details class="archive-extra"><summary>想继续查原件与异常记录</summary><p class="help-note">以下是补充阅读，可以按兴趣查看，不影响进入最后的决定。</p>${archiveFiles(ARCHIVE.filter(d=>d.gate==='vault').map(d=>d.id))}</details></section>`;
    const ids=k==='mirror'?['radio-index','programme','loan','forum','letter-liang']:['board-index','handover','positions','cabinet-note','current-list'];
    return `<div class="${k==='board'?'workbench-brand':'mirror-banner'}"><strong>${titles[k]}</strong><span>本地保全副本 · 与公开官网分开存放</span></div><section class="panel"><h1>${titles[k]}</h1><p>${k==='mirror'?'周栩：先试试旧硬盘里的广播索引。残页可能就在剪报袋里。其他文件也都留着，可以随时回看。':'先看交接便笺和今年的名单。要打开档案柜，将灯位对照与换柜记录放在一起看。'}</p>${archiveFiles(ids)}<div class="dialog-actions"><a class="button-link" href="#search?scope=private">检索留存资料</a><a class="button-link" href="#${k==='mirror'?'board':'vault'}">${k==='mirror'?'理事工作台':'历史档案柜'} →</a></div>${k==='board'?'<details class="archive-extra"><summary>其他留存附件 · 可继续探索</summary>'+archiveFiles(['mentor-mail','arrival','rules','bait','effigy','chant','eye-catalogue'])+'</details>':''}</section>`;
  }
  if(k==='board'){
    let body;
    if(state.chat.evidence['clerk-intro']==='carbon'&&(!GameCore.tilesComplete(state)||!state.visited.includes('night-leaf')))body='<p>折页：复写联的来源对上了。还缺同一袋传习页的夹页，先从周栩的广播索引找到它。</p><a class="button-link primary" href="#doc/radio-index">打开广播索引 →</a><a class="button-link" href="#search?scope=private">已复原残页，去检索 →</a>';
    else if(state.chat.evidence['clerk-intro']==='carbon')body='<p>折页：复写联上的压字和原件一致。我把副本入口发过来了，旧工作证和口令已经替你处理好。</p><button class="primary" data-action="open-board">打开折页发来的副本</button>';
    else if(state.chat.answers['zhou-source'])body='<p>周栩已经介绍了资料员“折页”。先在会话里发送梁老师的复写联，对方核对来源后就会发来入口。</p><a class="button-link primary" href="#chat/clerk">回到折页的会话 →</a>';
    else if(state.visited.includes('carbon'))body='<p>你已经找到梁老师的复写联。周栩看过同一张单子，正在等你回复，之后会介绍能提供工作台副本的资料员。</p><a class="button-link primary" href="#chat/zhou">查看周栩的新消息 →</a>';
    else body='<p>周栩：有人愿意提供副本，但我们得先核对材料是不是同一份。梁老师的邮件里提到一张留有压字的复写联，先从那里看起。</p><a class="button-link primary" href="#doc/letter-liang">阅读梁老师的邮件 →</a>';
    return `<section class="panel search-panel gate-panel"><span class="eyebrow">联系人提供的资料</span><h1>${titles[k]}</h1>${body}<p class="help-note">分享者确认材料来源后，将开放此文件夹。</p></section>`;
  }
  return `<section class="panel search-panel gate-panel"><span class="eyebrow">LOCAL ARCHIVE / 本地资料</span><h1>${titles[k]}</h1><p>${k==='mirror'?'周栩分享了广播站旧资料。提取码沿用旧备份口令：毕业晚会那晚广播正式停下来的时刻，四位数字。':'把换柜记录的三次停灯方位与灯位标签对应，依次取三个数字。'}</p><form id="gate-form" data-gate="${k}"><label for="password">${k==='vault'?'开柜顺序（三位数字）':'分享提取码（四位数字）'}</label><input id="password" name="password" autocomplete="off" inputmode="numeric" maxlength="30" required><div class="dialog-actions"><button class="primary">打开资料</button></div><p id="form-error" class="error" role="alert"></p></form>${k==='vault'?'<div class="gate-references"><a href="#doc/positions">回看灯位对照</a><a href="#doc/cabinet-note">回看三次停灯记录</a></div>':''}<p class="help-note">提取码由分享者设置，可在微信中查看对方留言。</p><a href="#${k==='mirror'?'home':'board'}">← 返回${k==='mirror'?'学校官网':'工作台'}</a></section>`;
}
function casePage(){
 if(!state.vault)return archiveShell('核对往来','<div class="archive-lock"><h2>原件仍在核对中</h2><p>周栩和折页正在核对材料来源。</p><a href="#'+(state.board?'vault':state.mirror?'mirror':'home')+'">回到当前文件 →</a></div>',{folder:state.board?'board':'mirror'});
 const i=state.reviewStep,c=CASE_CHAPTERS[i],done=!!state.caseRead[c.id],verified=GameCore.verified(state,c.id);
 const tasks={name:{who:'zhou',question:'谁要求把知遥从外部记录里删掉？',text:'人数矛盾并不能确定经办人。周栩在等一份直接记录执行范围和经办人的材料。'},voice:{who:'shen',question:'这真的是知遥近期的消息吗？',text:'沈嘉宁在等包含原始页与封存附页的值班簿。比较封面日期、正文日期和同号交接，不要只看被摘出的“我活着”。'},arrival:{who:'clerk',question:'哪张通知安排的是接收车辆？',text:'先看通知写给谁、安排的是哪类活动，再比较同类通知的日期。把你判断会执行的车辆安排发给折页。'}};
 const t=tasks[c.id];
 return archiveShell('核对往来 · 2028-06-15',`<section class="reading-room"><nav class="reading-progress" aria-label="调查进度">${CASE_CHAPTERS.map((x,n)=>`<span ${i===n?'aria-current="step"':''}>${state.caseRead[x.id]?'✓':n+1} ${x.label}</span>`).join('')}</nav><article class="reading-scene"><div class="file-discussion-header"><b>参与人：周栩、你</b><br>关联原件与核实结果附在各段下方</div><span class="eyebrow">${i+1} / 3</span><h1>${c.title}</h1><div class="reading-prose">${c.paragraphs.slice(0,2).map(p=>`<p>${esc(p)}</p>`).join('')}</div>${!verified?`<section class="pending-question"><h2>${t.question}</h2><p>${t.text}</p><a class="button-link primary" href="#${c.id==='voice'&&!state.visited.includes('bailu-now')?'doc/bailu-now':'chat/'+t.who}">${c.id==='voice'&&!state.visited.includes('bailu-now')?'先读沈嘉宁发给周栩的回信 →':'打开微信核实 →'}</a><p class="help-note">在会话输入栏旁点 ＋，从已读文件里挑一份发送。选错可以继续核对。</p></section>`:`<div class="reading-prose">${c.paragraphs.slice(2).map(p=>`<p>${esc(p)}</p>`).join('')}</div><div class="reading-reply">${c.reply.map(p=>`<p>${esc(p)}</p>`).join('')}</div>`}<details class="reading-sources" ${!verified?'open':''}><summary>这一段相关的原始材料</summary><p>可以重新打开，比较形成时间、写给谁，以及记录了什么。阅读本身不会替你完成核实。</p>${archiveFiles(c.documents.concat(i===2?['arrival-cover','campus-open']:[]).filter(id=>doc(id)))}</details><details class="reading-sources"><summary>继续了解这些人的经历</summary><ul class="related-list">${c.extras.map(([id,label])=>`<li><a href="#${id.includes('/')?id:'doc/'+id}">${label}</a></li>`).join('')}</ul></details><div class="reading-actions">${i?'<button data-action="previous-chapter">← 上一段</button>':''}${verified&&i<2?`<button class="primary" data-action="read-chapter" data-id="${c.id}">核对好了，继续看下一件事 →</button>`:verified&&!done?'<button class="primary" data-action="read-chapter" data-id="arrival">三件事都核实了 →</button>':''}</div>${i===2&&done?'<div class="verified-box" tabindex="-1"><h2>接下来，怎么做？</h2><p>原件和来源已经分别核实。接下来由你决定。</p><div class="ending-choices"><button class="primary" data-action="submit-case">和周栩一起移交材料</button><button data-action="retreat">告诉周栩，我退出调查</button><a class="button-link" href="#invitation">查看独自赴约的条件</a></div></div>':''}</article><p class="reading-pause">核实记录已保留，可重新打开关联原件。</p></section>`,{folder:'case',mode:'preview'});
}
